server:
  port: 8092

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb

kafka:
  bootstrap-servers: 192.168.99.100:9092
  groupid:
    events: events-group
  topic:
    events: test
