server:
  port: 8091

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/testdb

endpoints:
  event-store:
    uri-base: http://event-store-srv:8090
    add-property-command: /commands/add-property-transaction

kafka:
  bootstrap-servers: kafka:9092
  groupid:
    events: events-group
  topic:
    events: test
